# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ "dm-snapshot" ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.kernelPackages = pkgs.linuxPackages;
  boot.extraModulePackages = [ ];

  hardware.graphics = {
    extraPackages = [ pkgs.amdvlk ];
  };

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/5bb9b5c1-75c0-4090-8122-f244514ba958";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/3114-B3A5";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/home/tijmen/Games" =
    { device = "/dev/disk/by-uuid/7b5b4d5e-7a6e-41f9-9e84-e70386ca8cab";
      fsType = "ext4";
    };

  fileSystems."/home/tijmen/Backup" =
    { device = "/dev/disk/by-uuid/5d1ec62c-ce54-479b-918c-909fa57ecaad";
      fsType = "ext4";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/71d3f41b-49de-43d1-bc6e-c7c28fda0861"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno1.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
