#! /bin/sh
xrandr --output DP-3 --mode 3840x2160 --scale 0.8x0.8
nitrogen --restore &
pgrep -x sxhkd > /dev/null || sxhkd &

# bspc subscribe monitor_add monitor_remove | while read -a msg ; do 
#     bspc wm -r & pkill -USR1 -x sxhkd 
# done

bspc monitor DP-3 -d 1 2 3 4 5

bspc config border_width         2
bspc config window_gap           2
bspc config top_paddig          30

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
